[env]
TERM = "xterm-256color"

[shell]
program = "zellij"

[window]
padding.x = 6
padding.y = 4
decorations = "Full"
opacity = 0.98
startup_mode = "Fullscreen"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
